const $=id=>document.getElementById(id);const today=Cadeira85.isoDate(new Date());
$('todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>{$('toast').hidden=true},1800)}
function pretty(iso){return new Date(`${iso}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});}
function render(){const all=Cadeira85.getBookings().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const activeToday=all.filter(b=>b.date===today&&b.status!=='cancelado');const pending=activeToday.filter(b=>b.status==='pendente').length;const revenue=activeToday.reduce((sum,b)=>sum+(Cadeira85.serviceById(b.serviceId)?.price||0),0);const totalSlots=Cadeira85.slots.length*Cadeira85.barbers.length;const ticket=activeToday.length?revenue/activeToday.length:0;
$('kpiBookings').textContent=activeToday.length;$('kpiPending').textContent=`${pending} pendente${pending===1?'':'s'}`;$('kpiRevenue').textContent=Cadeira85.money(revenue);$('kpiOccupancy').textContent=`${Math.round(activeToday.length/totalSlots*100)}%`;$('kpiTicket').textContent=Cadeira85.money(ticket);
const rows=$('bookingRows');rows.innerHTML='';all.filter(b=>b.date>=today).slice(0,20).forEach(b=>{const s=Cadeira85.serviceById(b.serviceId),barber=Cadeira85.barberById(b.barberId);const tr=document.createElement('tr');tr.innerHTML=`<td>${pretty(b.date)}</td><td><strong>${b.time}</strong></td><td><strong>${b.customer}</strong><br><small style="color:var(--muted)">${b.phone||''}</small></td><td>${s?.name||'—'}</td><td>${barber?.name||'—'}</td><td><span class="status ${b.status}">${b.status.toUpperCase()}</span></td><td><div class="actions">${b.status==='pendente'?`<button class="btn btn-secondary btn-small" data-action="confirm" data-id="${b.id}">Confirmar</button>`:''}${b.status!=='cancelado'?`<button class="btn btn-danger btn-small" data-action="cancel" data-id="${b.id}">Cancelar</button>`:''}</div></td>`;rows.append(tr);});
rows.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.action;Cadeira85.updateBooking(btn.dataset.id,{status:action==='confirm'?'confirmado':'cancelado'});toast(action==='confirm'?'Agendamento confirmado':'Agendamento cancelado');render();}));
const timeline=$('timeline');timeline.innerHTML='';const todayItems=all.filter(b=>b.date===today&&b.status!=='cancelado').sort((a,b)=>a.time.localeCompare(b.time));if(!todayItems.length){timeline.innerHTML='<div class="empty">Nenhum horário agendado hoje.</div>';}todayItems.forEach(b=>{const s=Cadeira85.serviceById(b.serviceId),barber=Cadeira85.barberById(b.barberId);const div=document.createElement('div');div.className='timeline-item';div.innerHTML=`<time>${b.time}</time><div><strong>${b.customer}</strong><small>${s?.name} • ${barber?.name}</small></div>`;timeline.append(div);});}
$('resetBtn').addEventListener('click',()=>{Cadeira85.resetDemo();toast('Demo restaurada');render();});render();
