const C=window.C85; const $=s=>document.querySelector(s);
function svc(id){return C.services.find(x=>x.id===id)}function barber(id){return C.barbers.find(x=>x.id===id)}
function statusLabel(s){return s==='confirmed'?'Confirmado':s==='cancelled'?'Cancelado':'Pendente'}
function paymentLabel(b){return b.paymentStatus==='signal_paid'?`Sinal ${C.currency(b.paidAmount)}`:b.paymentStatus==='paid'?`Pago ${C.currency(b.paidAmount)}`:'No local'}
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,1600)}
function change(id,status){const list=C.getBookings();const b=list.find(x=>x.id===id);if(b)b.status=status;C.setBookings(list);render();toast(status==='confirmed'?'Agendamento confirmado':'Agendamento cancelado')}
function render(){
  const all=C.getBookings().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)); const today=C.isoDate(new Date()); const day=all.filter(x=>x.date===today&&x.status!=='cancelled'); const pending=day.filter(x=>x.status==='pending').length; const revenue=day.reduce((a,b)=>a+b.price,0); const paid=day.reduce((a,b)=>a+(b.paidAmount||0),0); const occupancy=Math.min(100,Math.round(day.length/(C.times.length*C.barbers.length)*100));
  $('#kpiBookings').textContent=day.length;$('#kpiPending').textContent=`${pending} pendente${pending===1?'':'s'}`;$('#kpiRevenue').textContent=C.currency(revenue);$('#kpiPaid').textContent=C.currency(paid);$('#kpiOccupancy').textContent=occupancy+'%';
  $('#bookingRows').innerHTML=all.length?all.map(b=>`<tr><td>${C.formatDate(b.date)}</td><td><strong>${b.time}</strong></td><td>${b.customer}<br><small>${b.phone}</small></td><td>${svc(b.serviceId)?.name||'—'}</td><td>${barber(b.barberId)?.name||'—'}</td><td><span class="status-badge ${b.status}">${statusLabel(b.status)}</span></td><td><span class="status-badge payment">${paymentLabel(b)}</span></td><td><div class="action-row">${b.status!=='confirmed'?`<button class="icon-btn" data-confirm="${b.id}">Confirmar</button>`:''}${b.status!=='cancelled'?`<button class="icon-btn" data-cancel="${b.id}">Cancelar</button>`:''}</div></td></tr>`).join(''):`<tr><td colspan="8" class="empty">Nenhum agendamento.</td></tr>`;
  document.querySelectorAll('[data-confirm]').forEach(x=>x.onclick=()=>change(x.dataset.confirm,'confirmed'));document.querySelectorAll('[data-cancel]').forEach(x=>x.onclick=()=>change(x.dataset.cancel,'cancelled'));
  const timeline=day.sort((a,b)=>a.time.localeCompare(b.time));$('#timeline').innerHTML=timeline.length?timeline.map(b=>`<div class="timeline-item"><div class="timeline-time">${b.time}</div><div class="timeline-body"><strong>${b.customer} • ${svc(b.serviceId)?.name}</strong><small>${barber(b.barberId)?.name} • ${paymentLabel(b)}</small></div></div>`).join(''):'<div class="empty">Agenda livre hoje.</div>';
}
$('#todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('#resetBtn').onclick=()=>{localStorage.removeItem(C.storageKey);C.seed();render();toast('Demo resetada')};render();
